= Dokumentaion LF10b - Linux
:toc:

== Grundlegende Kommandos

- `whoami` - zeigt den aktuell angemeldeten Benutzer an
- `pwd` - zeigt das aktuelle Verzeichnis an
- `ls` - zeigt den Inhalt eines Verzeichnisses an
- `ls -a` - zeigt auch versteckte Dateien an
- `ls -l` - zeight ausführliche Informationen zu Dateien an
- `ls -t` - sortiert nach Änderungsdatum
- `ls -r` - kehrt Sortierreihenfolge um
- `cd <dir>` - _Change Directory_: wechselt in das Verzeichnis `<dir>`
- `cd` - Wechselt von jedem Ort aus ins Heimatverzeichnis des aktuellen Benutzers

== Pfadangaben

Pfadangaben sind die "Wegbeschreibungen" zu Dateien oder Verzeichnissen. Es gibt zwei Arten von Pfadangaben:

- *relative Pfadangaben* sind immer ausgehend vom aktuellen Verzeichnis, beginnen also *nie* mit einem Slash `/`. 
- *absolute Pfadangaben* sind immmer ausgehend vom _Wurzelverzeichnis_ `/` und beginnen daher *immer* mit einem Slash `/`.

== Sonderzeichen 

Bestimmte Zeichen haben eine Sonderbedeutung für die BASH. Eins der wichtigsten Sonderzeichen ist der Leerschritt / Space. Dies ist das *Trennzeichen* für die Shell, trennt also z.B. ein Kommando und seine Optionen bzw. Argumente.

Andere Sonderzeichen sind z.B.:

- `*` _Asterisk_ steht für ein beliebiges Zeichen, dass *beliebig oft* vorkommen darf
- `?` _Fragezeichen_ steht für ein beliebiges Zeichen, dass *exakt einmal* vorkommen darf
- `!` History Expansion (s.u.)
- `$` Zeichen für eine Substitution (Variabelsubstitution, Kommandosubstitution ...)
- `\` _Escape Character_ maskiert das direkt darauf folgende Zeichen, hindert die Shell also daran, dieses mit einer Sonderbedeutung zu interpretieren
- `~` _Tilde_ symbolisiert das Heimatverzeichnis des aktuellen Benutzers
- etc.

=== Escapen / Maskieren von Sonderzeichen

Sonderzeichen können ihrer Sonderbedeutung durch _Escapen / Maskieren_ entledigt werden. Bzw. hindern wir die Shell daran dieses Sonderzeichen zu interpretieren.

Sonderzeichen können entweder mit dem Backslash `\` maskiert werden, oder in einfache (`'`) oder doppelte (`"`) Anführungszeichen gesetzt werden.

== Dateioperationen

== touch

Ändert den Zeitstempel einer vorhandenen Datei bzw. erstellt eine neue Datei ohne Inhalt.

 touch newfile.txt

== mkdir

Mit dem Kommando `mkdir` können Verzeichnisse erstellt werden. Sollen in einem Rutsch mehrere Unterverzeichnisse erstellt werden, übergeben wir zusätzlich den Schalter `-p`.

 mkdir my_dir

 mkdir -p ~/my_dir/sub_dir/sub_sub_dir

== cp

- `cp <quelle> <ziel>` kopiert `<quelle>` nach `<ziel>`. Hierbei sind beides Dateien. Existiert `<ziel>` nicht, wird es erstellt, ansonsten ungefragt überschrieben.
- `cp -i <quelle> <ziel>` so wird vor dem Überschreiben eine Nachfrage eingeblendet
- `cp -r <verzeichnis> <ziel>` beim Kopieren von Verzeichnissen muss die Aktion _rekursiv_ durchgeführt werden (Option `-r`)
- `cp -u <quelle> <ziel>` ersetzt `<ziel>` nur dann, wenn `<quelle>` neuer ist bzw. überhaupt Unterschiede vorhanden sind
- `cp -p <quelle> <ziel>` behält Dateiatribute (Bestizer, Rechte, Timestamp) bei
- `cp -a <quelle> <ziel>` behält auch Dateiatribute bei, enthält zusätzlich die Option `-r`.

== mv

Mit `mv` können Dateien verschoben und umbenannt werden.

- `mv <quelle> <ziel>` verschiebt `<quelle>` nach `<ziel>`
- `mv <quelle> <ziel>` benennt `<quelle>` in `<ziel>` um
- Für `mv` gibt es keine Option `-r`. Sowohl `<quelle>` als auch `<ziel>` können Verzeichnisse sein. 
- auch für `mv` gibt es die Option `-i`

== rm

- `rm <datei>` löscht `<datei>` ohne Nachfrage
- `rm -r <verzeichnis>` löscht `<verzeichnis>`
- auch für `rm` gibt es die Option `-i`

== rmdir

löscht *leere* Verzeichnisse

== Wichtige Verzeichnisse

- `/home/` - enthält die Heimatverzeichnisse der unpriveligierten Benutzer
- `/home/tux/` - Heimatverzeichnis des Benutzers `tux`
- `/home/lisa/` - Heimatverzeichnis der Benutzerin `lisa`
- `/etc` - enthält sämtliche systemweiten Konfigurationsdateien

== Variablen

* es gibt zwei Arten von Variablen: 
** *Shellvariablen*: sind nur in der aktuellen Shell gültig
** *Umgebungsvariablen*: sind in allen Shells gültig (werden komplett in Großbuchstaben geschrieben [Konvention]), müssen in bestimmten Dateien konfiguriert werden (z.B. `~/.bashrc`, `~/.profile` etc.)
* mit dem Kommado `export` kann eine Shellvariable auch in Subshells verfügbar gemacht werden

== Subshells

Eine Shell, die innerhalb einer anderen Shell gestartet wird. Passiert relativ oft, ohne dass wir es direkt merken, z.B. bei der _Kommandosubstitution_, beim Aufruf von Funktionen in Skripten usw. Eine Subshell ist abhängig von der Elternshell. Wird die Elternshell geschlossen, werden gleichzeitig auch alle Subshells geschlossen.

== Konfigurationsdateien

* Systemweite Konfigurationsdateien: liegen immer unter `/etc`, sind für alle Benutzer gültig (z.B. `/etc/bash.bashrc`)
* Benutzerspezifische Konfigurationsdateien: liegen immer im Heimatverzeichnis des Benutzers, beginnen immer mit einem Punkt (`.`) oder liegen in einem Verzeichnis, das mit einem Punkt beginnt (z.B. `~/.bashrc`, `~/.config/htop`)
* Einträge in den benutzerspezifischen Konfigurationsdateien überschreiben ggf. Einträge aus der systemweiten
* So können Bentzer selbst gewisse Einstellungen vorhnehmen ohne Root-Rechte haben zu müssen, z.B. Aliase erstellen, die BASH konfigurieren...

== Aliase

* Aliase können z.B. dazu verwendet werden, häufig genutzte Kommandos inklusive deren Optionen abzukürzen:
* z.B. bewirkt folgende Aliasdefinietion: `alias ll='ls -l'`, dass wir nun nur noch `ll` eingeben müssen, um das Kommando `ls -l` auszuführen
* Aliase werden in Dateien konfiguriert, standardmässig in der `~/.bashrc` oder besser noch in der Datei `~/.bash_aliases`

== Textströme 

== UNIX-Philosophie

1. Schreibe Programme so, dass sie *eine* Aufgabe erledigen, und diese gut machen
2. Schreibe Programme so, dass sie zusammenarbeiten
3. Schreibe Programme so, dass sie Textströme verarbeiten, denn Text ist eine universelle Schnittstelle

== Standardkanäle 

- Standardeingabekanal - `stdin` - Kanalnr. 0
- Standardausgabekanal - `stdout` - Kanalnr. 1
- Standardfehlerkanal - `stderr` - Kanalnr. 2

== Redirect - Kanäle in Dateien umleiten

Mit einem Redirect kann ein Datenstrom in eine *Datei* umgeleitet werden.

- `>` Mit einem _einfachen_ Redirect wird der Standardausgabekanal oder der Standardfehlerkanal in eine Datei umgeleitet. Die Datei muss vorher nicht existiert haben, sie wird ggf. erzeugt. Eine bereits bestehende Datei wird zuerst geleert/der Inhalt gelöscht und anschließend mit dem Inhalt des Datenstroms beschrieben.

 ls /etc 1> ausgabe_ls.txt     # stdout(1) in datei
 ls /etc > ausgabe_ls.txt     # stdout(1) in datei

 ls /gibtsnicht 2> fehler_ls.txt     # stderr(2) in datei

- `>>` Mit einem _doppelten_ (anhängenden) Redirect wird der Inhalt des Datenstroms (`stdout` oder `stderr`) an eine bereits bestehende Datei angehängt. Eine nicht existierende Datei würde erzeugt werden.
- `&>` So werden sowohl `stdout` als auch `stderr` in eine Datei umgeleitet

 ls /etc /gibtsnicht &> ausgabe_und_fehler.txt

`sterr` wird in `stdout` umgeleteitet und dann `stdout` in datei
das `&1` ist nötig, damit der Shell klar ist, dass der Kanal 1 gemeint ist
ansonsten würde die Datei `1` erstellt werden

 ls /etc /gibtsnicht > ausgabe_und_fehler.txt 2>&1    

- `<` Mit dem umgedrehten Redirect kann der Inhalt einer Datei an den Eingabekanal eines Kommandos geleitet werden

 mail -s Mail_Subject empfaenger@mail.example < mailinhalt.txt

== Pipe

Mit der Pipe `|` wird der Ausgabekanal eines Kommandos an den Eingabekanal eines weiteren Kommandos umgeleitet.

- `<Kommando1> | <kommando2>`

 ls -l /etc | less
 grep alias ~/.bashrc | grep -v `#`

== Filterkommandos

Wir nutzen Filterkommandos um aus einem Textstrom den Inhalt zu herauszufiltern, den wir haben wollen 

=== grep

Alle Zeilen anzeigen, die das Pattern `alias` enthalten. Es wird immer die gesamte Zeile ausgegeben in der das Pattern vorkommt.

 grep 'alias' ~/.bashrc

Gesamten Inhalt der Datei `~/.bashrc` anzeigen, Kommentarzeilen *nicht* mit ausgeben

 grep -v `#` ~/.bashrc 

- `grep -i <pattern>`: Gross- und Kleinschreibung von `<pattern>` ist egal
- `grep -n <pattern>`: Anzeige der Zeilennummer, in der `<pattern>` gefunden wurde
- `grep -r <pattern> dir/`: Rekursive Suche, so kann über alle Dateien in einem Verzeichnis _gegrept_ werden
- `grep -v <pattern>`: _inVert match_: Ausgabe wird _invertiert_, also nur die Zeilen ausgegeben, in denen `<pattern>` *nicht* vorkommt
- `grep -c <pattern>`: gibt nicht die Zeilen aus, sondern nur die Anzahl der Zeilen in denen `<pattern>` vorkommt

=== cut

Mit `cut` können wir Spalten/Felder/_Fields_ aus tabellarisch aufgebauten Dateien _ausschneiden_ bzw. filtern. Die wichtigen Optionen für `cut` sind `-d` zur Angabe des Trennzeichens (_Delimiter_) und `-f` zur Angabe der Spalte (_Field_). Bsp.:

Ausschließlich die Login-Namen anzeigen lassen:

 cut -d: -f1 /etc/passwd

=== weitere Filterkommandos

- `tr`: übersetzt ein Zeichen in einem Textstrom (es können keine Dateien als Argument übergeben werden) in ein anderes/löscht dieses etc... 

 tr a A < datei.txt  # wandelt jedes kleine a in ein grosses A um

- `wc`: gibt die Anzahl der Zeilen, Wörter und Bytes einer Datei an 

 wc -l /etc/passwd`  # Anzahl Zeilen der Datei /etc/passwd

== Benutzer und Gruppen

Es gibt zwei Arten von Benutzern:
* Systembenutzer/Pseudobenutzer
* Reale Benutzer

=== Dateien der Benutzerverwaltung

* `/etc/passwd`: Liste aller Benutzer auf dem System, tabellarischer Aufbau, Manpage `man 5 passwd`, von allen lesbar
* `/etc/shadow`: Passwörter der Benutzer, gesaltet und gehasht, Ablaufdaten der Passwörter
* `/etc/group`: Liste aller Gruppen und deren Mitglieder
* `/etc/gshadow`: Passwörter für Gruppen, wird eigentlich nicht verwendet

=== Benutzer anlegen

 useradd karl
  
Obiges Kommando erzeugt den Benutzer `karl`, es wird jedoch kein Heimatverzeichnis erstellt und die Shell ist die `/bin/sh`

Mit folgendem Kommando wird der Benutzer `tux` mit eigenem Heimatverzeichnis und darin enthaltener Standarddateien (Kopie von `/etc/skel`) erzeugt, im Kommentarfeld der Name `Tux Tuxedo` und der BASH als Login Shell:

 useradd -m -c 'Tux Tuxedo' -s /bin/bash tux

Anschließend muss mit dem Kommando `passwd tux` (mit root-Rechten) noch ein Passwort für `tux` erstellt werden.

Das interaktive Kommando `adduser` unter Debian ist ein Wrapper um `useradd`, welches zusätzlich ein Passswort erstellt.

=== Benutzer ändern

Mit dem Kommando `usermod` können Eigenschaften von Benutzern geändert werden. Die Optionen sind sehr ähnlich zu `useradd`.

=== Gruppen anlegen

Gruppe `gfn` erzeugen:

 groupadd gfn

Benutzer `tux` der Gruppe `gfn` hinzufügen:

 usermod -aG gfn tux

Wichtig ist hier das `-a`, ansonsten werden alle anderen Gruppenzugehörigkeiten von `tux` gelöscht.

**Wichtig:** Gruppenzugehörigkeiten werden erst aktiv, wenn sich der Benutzer einmal komplett vom System ab- und wieder angemeldet hat.

=== Benutzer ermöglichen, sudo auszuführen

Damit ein Benutzer mittels `sudo` root-Rechte erlangen kann, fügen wir diesen Benutzer der Gruppe `sudo` hinzu:

 usermod -aG sudo tux

Anschliessend kann der Benutzer `tux` mittels `sudo` root-Rechte erlangen
