= Dokumentaion LF10b - Linux
:toc:

== Grundlegende Kommandos

- `whoami` - zeigt den aktuell angemeldeten Benutzer an
- `pwd` - zeigt das aktuelle Verzeichnis an
- `ls` - zeigt den Inhalt eines Verzeichnisses an
- `ls -a` - zeigt auch versteckte Dateien an
- `ls -l` - zeight ausführliche Informationen zu Dateien an
- `ls -t` - sortiert nach Änderungsdatum
- `ls -r` - kehrt Sortierreihenfolge um
- `cd <dir>` - _Change Directory_: wechselt in das Verzeichnis `<dir>`
- `cd` - Wechselt von jedem Ort aus ins Heimatverzeichnis des aktuellen Benutzers

== Pfadangaben

Pfadangaben sind die "Wegbeschreibungen" zu Dateien oder Verzeichnissen. Es gibt zwei Arten von Pfadangaben:

- *relative Pfadangaben* sind immer ausgehend vom aktuellen Verzeichnis, beginnen also *nie* mit einem Slash `/`. 
- *absolute Pfadangaben* sind immmer ausgehend vom _Wurzelverzeichnis_ `/` und beginnen daher *immer* mit einem Slash `/`.

== Sonderzeichen 

Bestimmte Zeichen haben eine Sonderbedeutung für die BASH. Eins der wichtigsten Sonderzeichen ist der Leerschritt / Space. Dies ist das *Trennzeichen* für die Shell, trennt also z.B. ein Kommando und seine Optionen bzw. Argumente.

Andere Sonderzeichen sind z.B.:

- `*` _Asterisk_ steht für ein beliebiges Zeichen, dass *beliebig oft* vorkommen darf
- `?` _Fragezeichen_ steht für ein beliebiges Zeichen, dass *exakt einmal* vorkommen darf
- `!` History Expansion (s.u.)
- `$` Zeichen für eine Substitution (Variabelsubstitution, Kommandosubstitution ...)
- `\` _Escape Character_ maskiert das direkt darauf folgende Zeichen, hindert die Shell also daran, dieses mit einer Sonderbedeutung zu interpretieren
- `~` _Tilde_ symbolisiert das Heimatverzeichnis des aktuellen Benutzers
- etc.

=== Escapen / Maskieren von Sonderzeichen

Sonderzeichen können ihrer Sonderbedeutung durch _Escapen / Maskieren_ entledigt werden. Bzw. hindern wir die Shell daran dieses Sonderzeichen zu interpretieren.

Sonderzeichen können entweder mit dem Backslash `\` maskiert werden, oder in einfache (`'`) oder doppelte (`"`) Anführungszeichen gesetzt werden.

== Dateioperationen

== touch

Ändert den Zeitstempel einer vorhandenen Datei bzw. erstellt eine neue Datei ohne Inhalt.

 touch newfile.txt

== mkdir

Mit dem Kommando `mkdir` können Verzeichnisse erstellt werden. Sollen in einem Rutsch mehrere Unterverzeichnisse erstellt werden, übergeben wir zusätzlich den Schalter `-p`.

 mkdir my_dir

 mkdir -p ~/my_dir/sub_dir/sub_sub_dir

== cp

- `cp <quelle> <ziel>` kopiert `<quelle>` nach `<ziel>`. Hierbei sind beides Dateien. Existiert `<ziel>` nicht, wird es erstellt, ansonsten ungefragt überschrieben.
- `cp -i <quelle> <ziel>` so wird vor dem Überschreiben eine Nachfrage eingeblendet
- `cp -r <verzeichnis> <ziel>` beim Kopieren von Verzeichnissen muss die Aktion _rekursiv_ durchgeführt werden (Option `-r`)
- `cp -u <quelle> <ziel>` ersetzt `<ziel>` nur dann, wenn `<quelle>` neuer ist bzw. überhaupt Unterschiede vorhanden sind
- `cp -p <quelle> <ziel>` behält Dateiatribute (Bestizer, Rechte, Timestamp) bei
- `cp -a <quelle> <ziel>` behält auch Dateiatribute bei, enthält zusätzlich die Option `-r`.

== mv

Mit `mv` können Dateien verschoben und umbenannt werden.

- `mv <quelle> <ziel>` verschiebt `<quelle>` nach `<ziel>`
- `mv <quelle> <ziel>` benennt `<quelle>` in `<ziel>` um
- Für `mv` gibt es keine Option `-r`. Sowohl `<quelle>` als auch `<ziel>` können Verzeichnisse sein. 
- auch für `mv` gibt es die Option `-i`

== rm

- `rm <datei>` löscht `<datei>` ohne Nachfrage
- `rm -r <verzeichnis>` löscht `<verzeichnis>`
- auch für `rm` gibt es die Option `-i`

== rmdir

löscht *leere* Verzeichnisse

== Wichtige Verzeichnisse

- `/home/` - enthält die Heimatverzeichnisse der unpriveligierten Benutzer
- `/home/tux/` - Heimatverzeichnis des Benutzers `tux`
- `/home/lisa/` - Heimatverzeichnis der Benutzerin `lisa`
- `/etc` - enthält sämtliche systemweiten Konfigurationsdateien

== Variablen

* es gibt zwei Arten von Variablen: 
** *Shellvariablen*: sind nur in der aktuellen Shell gültig
** *Umgebungsvariablen*: sind in allen Shells gültig (werden komplett in Großbuchstaben geschrieben [Konvention]), müssen in bestimmten Dateien konfiguriert werden (z.B. `~/.bashrc`, `~/.profile` etc.)
* mit dem Kommado `export` kann eine Shellvariable auch in Subshells verfügbar gemacht werden

== Subshells

Eine Shell, die innerhalb einer anderen Shell gestartet wird. Passiert relativ oft, ohne dass wir es direkt merken, z.B. bei der _Kommandosubstitution_, beim Aufruf von Funktionen in Skripten usw. Eine Subshell ist abhängig von der Elternshell. Wird die Elternshell geschlossen, werden gleichzeitig auch alle Subshells geschlossen.

== Konfigurationsdateien

* Systemweite Konfigurationsdateien: liegen immer unter `/etc`, sind für alle Benutzer gültig (z.B. `/etc/bash.bashrc`)
* Benutzerspezifische Konfigurationsdateien: liegen immer im Heimatverzeichnis des Benutzers, beginnen immer mit einem Punkt (`.`) oder liegen in einem Verzeichnis, das mit einem Punkt beginnt (z.B. `~/.bashrc`, `~/.config/htop`)
* Einträge in den benutzerspezifischen Konfigurationsdateien überschreiben ggf. Einträge aus der systemweiten
* So können Bentzer selbst gewisse Einstellungen vorhnehmen ohne Root-Rechte haben zu müssen, z.B. Aliase erstellen, die BASH konfigurieren...

== Aliase

* Aliase können z.B. dazu verwendet werden, häufig genutzte Kommandos inklusive deren Optionen abzukürzen:
* z.B. bewirkt folgende Aliasdefinietion: `alias ll='ls -l'`, dass wir nun nur noch `ll` eingeben müssen, um das Kommando `ls -l` auszuführen
* Aliase werden in Dateien konfiguriert, standardmässig in der `~/.bashrc` oder besser noch in der Datei `~/.bash_aliases`

== Textströme 

== UNIX-Philosophie

1. Schreibe Programme so, dass sie *eine* Aufgabe erledigen, und diese gut machen
2. Schreibe Programme so, dass sie zusammenarbeiten
3. Schreibe Programme so, dass sie Textströme verarbeiten, denn Text ist eine universelle Schnittstelle

== Standardkanäle 

- Standardeingabekanal - `stdin` - Kanalnr. 0
- Standardausgabekanal - `stdout` - Kanalnr. 1
- Standardfehlerkanal - `stderr` - Kanalnr. 2

== Redirect - Kanäle in Dateien umleiten

Mit einem Redirect kann ein Datenstrom in eine *Datei* umgeleitet werden.

- `>` Mit einem _einfachen_ Redirect wird der Standardausgabekanal oder der Standardfehlerkanal in eine Datei umgeleitet. Die Datei muss vorher nicht existiert haben, sie wird ggf. erzeugt. Eine bereits bestehende Datei wird zuerst geleert/der Inhalt gelöscht und anschließend mit dem Inhalt des Datenstroms beschrieben.

 ls /etc 1> ausgabe_ls.txt     # stdout(1) in datei
 ls /etc > ausgabe_ls.txt     # stdout(1) in datei

 ls /gibtsnicht 2> fehler_ls.txt     # stderr(2) in datei

- `>>` Mit einem _doppelten_ (anhängenden) Redirect wird der Inhalt des Datenstroms (`stdout` oder `stderr`) an eine bereits bestehende Datei angehängt. Eine nicht existierende Datei würde erzeugt werden.
- `&>` So werden sowohl `stdout` als auch `stderr` in eine Datei umgeleitet

 ls /etc /gibtsnicht &> ausgabe_und_fehler.txt

`sterr` wird in `stdout` umgeleteitet und dann `stdout` in datei
das `&1` ist nötig, damit der Shell klar ist, dass der Kanal 1 gemeint ist
ansonsten würde die Datei `1` erstellt werden

 ls /etc /gibtsnicht > ausgabe_und_fehler.txt 2>&1    

- `<` Mit dem umgedrehten Redirect kann der Inhalt einer Datei an den Eingabekanal eines Kommandos geleitet werden

 mail -s Mail_Subject empfaenger@mail.example < mailinhalt.txt

== Pipe

Mit der Pipe `|` wird der Ausgabekanal eines Kommandos an den Eingabekanal eines weiteren Kommandos umgeleitet.

- `<Kommando1> | <kommando2>`

 ls -l /etc | less
 grep alias ~/.bashrc | grep -v `#`

== Filterkommandos

Wir nutzen Filterkommandos um aus einem Textstrom den Inhalt zu herauszufiltern, den wir haben wollen 

=== grep


=== cut
